wandb_version: 1

task:
  desc: null
  value: CODE
model_variant:
  desc: null
  value: Qwen/Qwen2.5-Coder-0.5B-Instruct
batch_size:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 1.0e-05
beta_1:
  desc: null
  value: 0.01
beta_2:
  desc: null
  value: 0.1
alpha:
  desc: null
  value: 5.0
_wandb:
  desc: null
  value:
    python_version: 3.12.1
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.46.3
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1733451454
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      - 98
      - 105
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      - 98
      - 105
      3:
      - 2
      - 16
      - 23
      - 61
      4: 3.12.1
      5: 0.17.8
      6: 4.46.3
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
